### ISSUE TITLE
Multi-monitor no longer works

### ISSUE THREAD

**Issue by udevnl** [lperez31/prime-select-hybrid#2]
First of all, excellent work by extending the prime-select script. Running it simply works!

Has anyone successfully used the Hybrid profile with any external monitors connected?

**Comment by udevnl** [comment]
On the HP Z-Book 17 G6 (which has Intel+Nvidia) and Ubuntu 18.04 multi-monitor is not working.

With hybrid, and the GPU not used for the display server, the computer will stay responsive, even if the GPU is 100% used for training. So this is why I want hybrid, so that I can use the computer while training on the GPU.

I found out the following:

- Using lightdm instead of gdm3 does not matter
- Changing the BIOS setting 'Graphics' has the following effect:
   - UMA: multi monitor works, but the NVIDIA chip gets disabled / no longer works
   - Hybrid: only laptop monitor, prime-select hybrid works and I can use the GPU in Tensorflow
   - Discrete: multi monitor works, prime-select hybrid is not using Intel as nvidia-smi shows Xorg and gnome
   - Auto: only laptop monitor, (did not try Tensorflow)

I have a theory that the is some hardware switch that connects the external monitor ports to the nvidia chip once it is enabled?!

If I find out anything useful I will post it here.

**Comment by udevnl** [comment]
Good news! I got it working and do NOT need the modified prime-select script.

I wrote a guide for anyone interested:


# Using the GPU for deep learning, integrated graphics for display(s)
This guide captures the solution to a painful search on how to get the following working:

* You have a laptop with a dedicated NVIDIA GPU chip and an Intel integrated graphics.
* You want to use the NVIDIA GPU for deep learning only
* You want the Intel chip to drive the displays / Linux graphical user interface
* You want to connect one or more external monitors

The above is a MUST if you want a responsive computer while the GPU is occupied with deep learning.

It seems to be quite difficult to get ALL of the above working...

This guide is based on the readme provided with the NVIDIA driver:
https://download.nvidia.com/XFree86/Linux-x86_64/450.66/README/randr14.html

## Prerequisites
This guide may apply to other situations as well, but was found working with the following setup: 
* Ubuntu 18.04
* Latest NVIDIA drivers from Ubuntu (v450.66 at this time)
* BIOS setting to 'Hybrid' graphics
* Lightdm (most likely a don't care, should work with default GDM3 too)

## Steps
1. Make sure NVIDIA is enabled
   * Type `nvidia-smi`, it should output some stats of your GPU and no errors
   * Otherwise enable NVIDIA using `sudo prime-select nvidia`, then reboot and retry `nvidia-smi`
2. Create a Xorg configuration file
   * Type `nvidia-xconfig --prime`
   * This will create the configuration file and also automatically fill in the BusID of your NVIDIA chip
3. Edit the Xorg configuration file
   * Type `sudo gedit /etc/X11/xorg.conf` (or use your own editor)
   * Below is my edited version, take note of the following:
     - I renamed the default devices to **DeviceIntel** and **DeviceNvidia** for readability
     - I made **DeviceNvidia** the inactive one and **DeviceIntel** the active one 
     - The option "SWCursor" is vital for me. Without it the mouse cursor will move very strangely 
    ```
    # nvidia-xconfig: X configuration file generated by nvidia-xconfig
    # nvidia-xconfig:  version 450.66
    
    Section "ServerLayout"
        Identifier     "Layout0"
        Screen      0  "Screen0"
        Inactive       "DeviceNvidia"
        InputDevice    "Keyboard0" "CoreKeyboard"
        InputDevice    "Mouse0" "CorePointer"
    EndSection
    
    Section "Files"
    EndSection
    
    Section "InputDevice"
        # generated from default
        Identifier     "Mouse0"
        Driver         "mouse"
        Option         "Protocol" "auto"
        Option         "Device" "/dev/psaux"
        Option         "Emulate3Buttons" "no"
        Option         "ZAxisMapping" "4 5"
    EndSection
    
    Section "InputDevice"
        # generated from default
        Identifier     "Keyboard0"
        Driver         "kbd"
    EndSection
    
    Section "Monitor"
        Identifier     "Monitor0"
        VendorName     "Unknown"
        ModelName      "Unknown"
        Option         "DPMS"
    EndSection
    
    Section "Device"
        Identifier     "DeviceNvidia"
        Driver         "nvidia"
        VendorName     "NVIDIA Corporation"
        BusID          "PCI:1:0:0"
    EndSection
    
    Section "Device"
        Identifier     "DeviceIntel"
        Driver         "modesetting"
        VendorName     "Unknown"
    
    ### VERY IMPORTANT! On Ubuntu 18 the mouse will behave strangely without this option!!!   
        Option         "SWCursor"
    EndSection
    
    Section "Screen"
        Identifier     "Screen0"
        Device         "DeviceIntel"
        Monitor        "Monitor0"
        DefaultDepth    24
        Option         "AllowEmptyInitialConfiguration" "True"
        SubSection     "Display"
            Depth       24
        EndSubSection
    EndSection
   ```
4. Save the Xorg configuration and restart your X server
   - Save all your work!
   - Type `sudo systemctl restart display-manager`
   - Your graphical session will restart, fingers crossed ;-)
   
After following these steps the NVIDIA GPU should no longer be used by the X server. You can check as follows:
1. The output of xrandr should no longer show any NVIDIA providers
   ```
   $ xrandr --listproviders
    Providers: number : 2
    Provider 0: id: 0x46 cap: 0x0 crtcs: 4 outputs: 3 associated providers: 0 name:modesetting
    Provider 1: id: 0x86 cap: 0x6, Sink Output, Source Offload crtcs: 3 outputs: 7 associated providers: 0 name:modesetting
   ```
2. The output of nvidia-smi should no longer show any running processes using the GPU.
   ```
    $ nvidia-smi 
    Thu Oct 29 10:26:26 2020       
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |                               |                      |               MIG M. |
    |===============================+======================+======================|
    |   0  Quadro RTX 5000     Off  | 00000000:01:00.0  On |                  N/A |
    | N/A   57C    P8    15W /  N/A |     26MiB / 16125MiB |      0%      Default |
    |                               |                      |                  N/A |
    +-------------------------------+----------------------+----------------------+
                                                                                   
    +-----------------------------------------------------------------------------+
    | Processes:                                                                  |
    |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
    |        ID   ID                                                   Usage      |
    |=============================================================================|
    |  No running processes found                                                 |
    +-----------------------------------------------------------------------------+
   ```
